openapi: 3.0.1
info:
  title: Product Service API
  description: API for managing products using AWS Lambda and API Gateway.
  version: "1.0"

servers:
  - url: https://lsaaozqyr5.execute-api.eu-west-1.amazonaws.com/prod
    description: Production Server
  - url: http://localhost:3000
    description: Local Development Server

paths:
  /products:
    get:
      summary: Get all products
      description: Returns a list of all available products.
      operationId: getProductsList
      tags:
        - Products
      responses:
        "200":
          description: Successful response with product list
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Product"
        "500":
          description: Internal Server Error

  /products/{productId}:
    get:
      summary: Get a product by ID
      description: Returns a specific product based on its ID.
      operationId: getProductById
      tags:
        - Products
      parameters:
        - name: productId
          in: path
          required: true
          description: ID of the product to retrieve
          schema:
            type: string
      responses:
        "200":
          description: Product found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Product"
        "404":
          description: Product not found
        "500":
          description: Internal Server Error

components:
  schemas:
    Product:
      type: object
      properties:
        id:
          type: string
          example: "6"
        name:
          type: string
          example: "Laptop"
        description:
          type: string
          example: "A high-end gaming laptop"
        price:
          type: number
          format: float
          example: 1299.99
